### ISSUE TITLE
Shamans not using totems

### ISSUE THREAD

**Issue by Silius01** [brian8544/mod-playerbots#10]
**Describe the bug**
Shaman bot  does not seem to be using totems

**Commit hash**
Latest commit

**To Reproduce**
Create a shaman bot
Get it high enough to get the first totem
Play with Bot

**Expected behavior**
Shaman to use totems

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 125.0.6422.141 

**Additional context**
Tried both caster and dps strategies. Have levelled a bot up to level 12 have not seen it summon a totem at all but other abilities are being used.

**Comment by Silius01** [comment]
Also note this is a character on my account that I am running as a Bot

**Comment by brian8544** [comment]
Hey, thanks for your report, but your doing it in the wrong repository.

Create a report here (https://github.com/liyunfan1223/mod-playerbots/issues). This repo is just for tinkering around and potentially sending my commits upstream if applicable :D
